### ISSUE TITLE
Img vertically error

### ISSUE THREAD

**Issue by twohreerains** [twohreerains/CSS_ERROR_GATHER#1]
### HTML CODE
```html
<!DOCTYPE HTML>
<html>

<head>
	<meta charset="utf-8">
	<link rel="stylesheet" href="css/style.css">
	<title>iMOOC</title>
</head>

<body>
	<nav>
		<div class="logo">
			<img src="images/logo.svg" alt="">
		</div>
	</nav>
</body>

</html>
```

### CSS CODE
```css
*{
	margin: 0px;
	padding: 0px;
}


nav{
	width:100%;
	height: 90px;
	display: flex;
	align-items: center;
	background-color: skyblue;

}

nav .logo img{
	height: 70px;
}
```

The picture was not in center.

I fixed it by this:
```css
nav .logo img{
	height: 70px;
	display:block;
}
```
